### ISSUE TITLE
0.1.2 wrongly state this is 1.0

### ISSUE THREAD

**Issue by AndreasDavour** [ChaosiumInc/QuestWorlds#10]
Hi

In section 0.1.1 it states this is version 0.1 of the licence, and then the next section 0.1.2 state it's 1.0 instead.

https://github.com/ChaosiumInc/QuestWorlds/blob/master/0.1_Legal_Information.md

**Comment by iancooper** [comment]
This is version 0.1 of the SRD and version 1.0 of the Open License. So the versioning is correct as it stands. Thanks for the observation though, it was worth checking.
