### ISSUE TITLE
Better masteries

### ISSUE THREAD

**Issue by iancooper** [ChaosiumInc/QuestWorlds#104]
Masteries have always been a pain point because:

(a) They prove notoriously difficult to explain
(b) They create a "whiff factor" with "fail bumped to success"

I have received an alternative approach to them I really like:

- Each 'bump' counts as an additional success. A bump comes from a critical, mastery, or story point.
- Roll and count successes. Most successes wins. On  a tie, highest roll.

To do this we need to drop fumbles altogether, but they had no real game meaning anyway. They were just folk wisdom from BRP.

It also gives us a 'difference' between two rolls without a table lookup. This enables us to take that 'difference' and play with it on advice on benefits and consequences, and yes, but etc. Yes, but is  not in the core rules but is part of our GM advice.

I **really** like this, as it fixes one of the issues that we struggled to improve on in this version.

**Comment by iancooper** [comment]
PS Dropping fumbles eliminates some horrible edge cases in the math anyway. IIRC RL's original system did not have fumbles, and I think Greg reflexively added them.

**Comment by iancooper** [comment]
I'm going to use the usual approach and put together a branch for this change, so that we can review what it looks like.

**Comment by iancooper** [comment]
Raised #106

**Comment by jrutila** [comment]
After reading #106 I must say this looks more clear and easier to teach to players. It also removes lots of "if the better result or same" text and kind of brings back the outcome levels through ranks (well, they were there before).

If, and that is a strong if, the fumble would still be there it could just remove one success. But yeah, it probably is not missed.

Does the rules allow now case where the player can use a SP after a crit vs fail (or fumble) roll? So three ranks from the roll, but use a SP to make it a four ranks win. I don't think this was possible earlier. Don't know why someone would like to do it, though.

**Comment by iancooper** [comment]
@jrutila Right. I think this gives us what I was after by dropping the tables, without the vague wording. I am still cleaning up the impact of fixing ranks with this.

I think that you could spend an SP to get an additional success, even if you had more already, to increase the rank. I don't think that is so important now, but I guess that it is possible

**Comment by iancooper** [comment]
It needs eyes once I am done, as it is a big enough change to leave some trailing ends behind that need cleaning up
