### ISSUE TITLE
Simple Typos/leftovers

### ISSUE THREAD

**Issue by Hteph** [ChaosiumInc/QuestWorlds#109]
In 2.5.8 there is still usage of the old +3/+6 instead of +5/+10

2.11 may have a markup error as its fold into the previous section instead of becoming a headline in the pdf.

3.2.2.1 The example uses breakout values of +1 and +2, it seems a bit contradictory to what is presented in 3.4 and 8.2 as the start of a Breakout ability always is +5

**Comment by iancooper** [comment]
@Hteph Thanks for these
