### ISSUE TITLE
[Fix] Formatting issues in PDF + language typo

### ISSUE THREAD

**Issue by rgodard** [ChaosiumInc/QuestWorlds#110]
Hello!

- In the second and fourth paragraph of 2.6.1, there are some formatting issues in the PDF.
![image](https://user-images.githubusercontent.com/7546170/102005128-38913480-3ccb-11eb-83bf-e0d42fb041e3.png)

- In the third paragraph of 2.7.1, as well.
![image](https://user-images.githubusercontent.com/7546170/102004830-3201bd80-3cc9-11eb-85b8-f2396fc846ec.png)
Now that I'm staring at the image, should this also say "one degree or -10 depending on how serious a handicap the flaw is."? The text saying "two degrees or -10" is also in the .md file.

- Section 2.11 doesn't appear as a header in the PDF, instead it appears in 2.10, at the end.
![image](https://user-images.githubusercontent.com/7546170/102005093-ff58c480-3cca-11eb-8794-e351ddb90c15.png)

- In 2.14, third paragraph, another formatting issue.
![image](https://user-images.githubusercontent.com/7546170/102004957-2ebb0180-3cca-11eb-8680-7244479a4986.png)

Thank you for your time. I hope the screenshot format is sufficient.

**Comment by iancooper** [comment]
Thanks for submitting these @rgodard
