### ISSUE TITLE
[Flow] Emphasise Rules Through Play (Basic Conflict Resolution with Character Generation, more complex rules afterwards)

### ISSUE THREAD

**Issue by simonphipp** [ChaosiumInc/QuestWorlds#111]
Reading the PDF, it does seem to be very rules-oriented.

I would rather see Section 2,4 follow on from 2.0 and then have the Character Generation sections 3.0 - 3.5 in the same chapter.

Also, it would flow better, in my opinion, to have 2.7 Flaws under 3.3 Flaws, perhaps as 3.3.1. 

Similarly, 2.1 Abilities and 2.2 Possessions and Equipment seem to belong more naturally in Chapter 3 Character Generation. 

So, I think it would work better with a short description of the basics of conflict resolution to be present earlier on, then have a Character Generation Section that covers some of the rules from a chargen and conflict resolution point of view, then to have the detailed breakdown of conflict resolution in a separate chapter. That way, you could have Conflict Resolution, Simple Contests and Long Contests as natural chapters following on from Character Generation/Conflict Resolution.

**Comment by Hteph** [comment]
I agree on that there is something odd about the order of stuff here, perhaps a left over from an earlier incarnation where it made sense. A refactoring of the structure as outline above makes sense I think.

And for the rules focus, I think it is great, if I want too cook up something own I want this skeleton as barebones as possible.

**Comment by iancooper** [comment]
The rules focus is deliberate as this is an SRD. The Core Rules book will have additional material.

It is a deliberate design choice to push character generation back further than is normal in other TTRPGs. It is difficult to define a character, in a system that has player defined traits over mechanics to produce characters, without first understanding what they mean. You not only need a base understanding of the mechanics, but what flaws or augments do for you in play, why you don't need abilities around wealth or equipment.

It can make sense for template based games to put character generation first, though it usually annoys the heck out of me, as I have to read that section with no understanding of what any of the choices being proffered mean.

**Comment by dscarpenter** [comment]
Rule organization is always a challenge. However you do it, someone will think it's wrong. Half the world wants to mechanics first and the other half wants to see chargen first. Same division on rules vs. setting narrative, but you don't have to worry about that with an SRD.

When it comes time to do the core rulebook, I highly suggest you take a look at Cyberpunk Red as a model - not for organization, but for excellent use of PDF functionality (links forward, links back, etc.). Whoever built their PDF architecture did a great job and set a high bar for digital products.

**Comment by iancooper** [comment]
Looking at Cortex Prime, which will be a significant competitor, it also adopts the strategy of rules, then character generation. As it adopts a similar model, player-defined traits, it does so, I believe, for the same reason. Going to close this one for now, with no action.
