### ISSUE TITLE
Suggestion: remove statement that flaws are abilities in section 2.1.1 Flaws

### ISSUE THREAD

**Issue by axzr** [ChaosiumInc/QuestWorlds#118]
In section 2.1.1, it begins by stating that flaws are abilities. This is confusing as by definition abilities are used to 'face challenges' and flaws 'should not be used to accomplish something'.

Also, in paragraph 3 of section 2.1.1, the second sentence implies that flaws are not abilities.

My suggestion would be to change the first paragraph to something like the following -

Your character may have one or more **flaws**. A **flaw** is a characteristic that the GM uses to hinder you from accomplishing something, or invokes to force you to act a certain way.

**Comment by Robin-Mitra** [comment]
In my opinion flaws should not be described as characteristics. This term only appears as distinguishing characteristic, what is completely different. 
On the other hand a flaw works exactly like an ability, except you don't want to succeed. I think that is easily explained.

**Comment by iancooper** [comment]
Rephrased to treat flaws as their own thing
