### ISSUE TITLE
Minor suggestion: remove duplication of the word 'roll' in section 2.1.2 Ratings and Masteries

### ISSUE THREAD

**Issue by axzr** [ChaosiumInc/QuestWorlds#120]
In section 2.1.2, paragraph 1, the word roll is used twice in close successsion. It's not a biggie.

Suggested change, to remove the duplication -

*QuestWorlds* **abilities** are scored on a **rating** of 1–20, representing the **target number (TN)** you need to roll or less to succeed in a **contest** (see §2.4 for more details).

**Comment by iancooper** [comment]
Thanks for all the comments, will look at what we need to do asap

**Comment by iancooper** [comment]
Thanks
