### ISSUE TITLE
Suggestions for section 2.3 Degrees

### ISSUE THREAD

**Issue by axzr** [ChaosiumInc/QuestWorlds#121]
Line 2 begins '**Degree** represent the scale' - I think that 'Degree' should be pluralised here.

Line 3 reads 'Your GM also uses the same **degree** as a modifier to a **base resistance** when determining the **resistance's** **TN**.'

I think this line is a bit ambiguous. A degree appears to be a specific number e.g. -5. I think what is meant here is that the GM uses the same 'scale of degrees'. I'm not quite sure how you rephrase this one I'm afraid!

The markdown for paragraph 2 is a bit broken. There's no full stop or white space at the end of sentence 1. It's not clear what's intended - 1 or 2 paragraphs. I'm guessing 1, and the full stop is just missing. There's also no full stop at the end of sentence 2.

This paragraph could be clearer, perhaps by calling out to the degree table that follows.

Note: I can see why degrees are zero-based, I think it would be clearer if they weren't but I see why they are :) Just need to make sure that the zero-base is applied universally (I've seen at least one section that is one-based - but that will be another ticket)

Finally, I suspect the last sentence needs some editing -- 'It is usually clear but you can use *decreasing* **degree** to refer to a subtraction and *higher* **increasing** to refer to an addition.'

*decreasing* **degree** and *higher* **increasing** don't seem to mesh well. I wonder if you meant *decreasing* **degree** and *increasing* **degree**?

**Comment by iancooper** [comment]
Fixed, thanks for the suggestions
