### ISSUE TITLE
Suggestion for 2.3.1 Degree Table

### ISSUE THREAD

**Issue by axzr** [ChaosiumInc/QuestWorlds#122]
Minor suggestion: I think it would be clearer if the degree table had separate columns for bonuses and penalties. I know the numbers are the same, I just see some few people being confused by say a zero degree meaning +5 _or_ -5.

e.g.

### 2.3.1 DEGREE TABLE

|Degree    |Bonus     |Penalty    |
|:------:|:------------:|:-------:|
|0|+5|-5|
|1|+10|-10|
|2|+15|-15|
|3|+M|-M|
|4|+M2|-M2|

**Comment by iancooper** [comment]
Changed, thanks for the suggestion
