### ISSUE TITLE
Suggestion for inner resources rule

### ISSUE THREAD

**Issue by Martigan1** [ChaosiumInc/QuestWorlds#123]
A rule to illustrate that the characters don't have unlimited inner resources like mana, willpower etc. is not a bad idea at all. I think all Heroquests game masters have made their own rules in this regard. An official rule would be welcome in Questworlds.

**Comment by scottalthoff** [comment]
I agree, this would be very helpful.

**Comment by jrutila** [comment]
Should this include a mention of external resources, like arrows, bullets, and money, as well?
Luckily, you don't have to track these resources in QuestWorlds. Maybe a mention of how you can use consequences, narrative guidance, and, in the end, credibility test to handle resource waning.

**Comment by Martigan1** [comment]
''Maybe a mention of how you can use consequences, narrative guidance, and, in the end, credibility test to handle resource waning.''  Just that and that would be great.

**Comment by Robin-Mitra** [comment]
>  I think all Heroquests game masters have made their own rules in this regard. 

Nope. I always try to keep it simple. In my opinion this is not relevant for rules, only for genre packs and such. It only depends on the setting, genre and style of your adventure whether physical or inner resources should be limited. Sometimes it can be essential for the suspense to restrict resources, mostly it would probably be a nuisance. In Glorantha for instance all major magic systems can be used unlimited.

**Comment by iancooper** [comment]
@Martigan1 We will cover this in the advice around genre packs in the Core Rules. It won't be a rule in the SRD.
