### ISSUE TITLE
[Question] 0.1.2 QuestWorlds Open Game License, Version 1.0

### ISSUE THREAD

**Issue by Robin-Mitra** [ChaosiumInc/QuestWorlds#125]
(h) 3.: "You must affix a complete copy of this License to any QuestWorlds Open Game Content that You Use and include the Copyright Notice detailed in Section 7 in all appropriate locations."

What exactly does this mean? In case I want to publish an adventure supplement. Would I quote Section 7 in the credits on page 1 and the complete license in the appendix? Or are there more "appropriate locations" like the download page or others? 

BTW I think section 7 should read as "This work was created..."

**Comment by iancooper** [comment]
Typically folks put the whole licence at the beginning
