### ISSUE TITLE
Typo in 3.4 Assigning Ability Ratings

### ISSUE THREAD

**Issue by scottalthoff** [ChaosiumInc/QuestWorlds#129]
"You can spend improvement points after a roll, so as to succeed and no fail."

Should be:

"You can spend improvement points after a roll, so as to succeed and not fail."

Do you still want people to use Improvement points the same way as Story Points?
Should this sentence change to:
"You can spend an improvement point after a roll to gain an additional success (see §2.4.6)"
This is similar to the sentence in 7.2 Success with a Story Point.

**Comment by iancooper** [comment]
Changed wording, it means you can alter the user's TN by upping their skill values.
