### ISSUE TITLE
[Enhancement]Add optional rule, critical is TN on roll under

### ISSUE THREAD

**Issue by iancooper** [ChaosiumInc/QuestWorlds#13]
One suggestion is that we add another option to roll over, that is to make the rolling the TN a critical as per Pendragon.

In Pendragon, a fumble is a 20. A critical is achieved when you roll equal to your TN, even if your TN is 20 and you roll a 20. 

This means that at abilities of 20 or over you can't naturally fumble (because a fumble at 1M+ automatically becomes a fail). You could of course be bumped down to a fumble with spare hero points, and you could of course fumble where masteries cancel out.

I think this is worth considering. Pendragon is the other D20 system from Chaosium and following the 'Pendragon Rules' for highest roll wins, would make sense.

**Comment by sciencefish** [comment]
It's worth considering, however it feels like we are incorporating Pendragon rules into this.

**Comment by iancooper** [comment]
I understand, though there is a flow that goes Prince Valiant -> QuestWorlds -> Pendragon ->BRP which we can't really avoid. Given that you cannot copyright mechanics, only expression of them, we are not inadvertently exposing Pendragon copyright.

**Comment by sciencefish** [comment]
What's a PR, can't see how to agree with you and commit this.

**Comment by iancooper** [comment]
Sorry, PR is short for Pull Request. You have been copied in as a reviewer here: https://github.com/ChaosiumInc/QuestWorlds/pull/15. You can see that it is linked above, in the issue history. Just click the green Open button

**Comment by iancooper** [comment]
You can use the PR to preview the change, and comment on it

**Comment by iancooper** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews
