### ISSUE TITLE
When calculating a Flaw's rating do you add breakouts to keywords to determine you highest ability?

### ISSUE THREAD

**Issue by scottalthoff** [ChaosiumInc/QuestWorlds#131]
In 3.4 Assigning Ability Ratings it is unclear if breakouts should be added to their keywords to determine your highest, second highest, and lowest ability.

Also does a flaw's rating change over time as you improve your abilities? If so I think in 3.4 the flaw paragraph should move after the improvement paragraph. In 8.2 Improving Your Character it would be good to note that flaws should be updated after improvements are made.

**Comment by scottalthoff** [comment]
My group has been doing.
1. Highest keyword with its highest breakout
2. Second highest keyword with its highest breakout
3. Lowest keyword

**Comment by iancooper** [comment]
Good question. It would reflect breakouts, but let's be explicit

**Comment by iancooper** [comment]
Fixed
