### ISSUE TITLE
Why is only one sidekick allowed at character creation?

### ISSUE THREAD

**Issue by scottalthoff** [ChaosiumInc/QuestWorlds#132]
3.1 As-You-Go Method says "You are restricted to only one sidekick."

Why is this the case? As long as the sidekick's abilities count towards your 12 ability and 3 flaw maximum I think it would be fine to have more than one sidekick.

Somewhat related in 6.5.1 Sidekick there is a bunch of creation text in there. Should sidekick creation move to somewhere in section 3 Character Creation?

**Comment by scottalthoff** [comment]
Also 6.5.3 Retainers should be 6.5.2

**Comment by scottalthoff** [comment]
Is there a need to distinguish between Sidekicks and Retainers?
It seems like you could just have followers and a follower could grant you 1 or more abilities each.

**Comment by iancooper** [comment]
Sidekicks are intended to represent genre characters who are accompanied by a secondary character. Unlike retainers who don't act independently "on camera", a sidekick can
