### ISSUE TITLE
Breakout ratings unclear - can they be improved or not?

### ISSUE THREAD

**Issue by AndreasDavour** [ChaosiumInc/QuestWorlds#135]
In _2.1.1.1 Breakouts_ you have "You write these specialized breakout abilities under the keyword, along with how much they’ve improved from the keyword" and then two examples at +5. It does not say they start at +5, which makes you wonder if you have to spend some points from somewhere on that.

In _3.4 Assigning Ability Ratings_ you have "A breakout from a keyword starts at +5. In some cases, you may treat your distinguishing characteristic as a breakout ability from a keyword in this case, treat it as a +10." and later in the same section "You cannot increase a breakout with improvement points." No issue there, but maybe that mention of breakouts starting at +5 would have been nice to mention in 2.1.1.1 also. That latter quote becomes problematic in relation to this section below.

In _8.2 Improving Your Character_ you have a list of two options to pick as an advance. The first bullet point say one advance may buy you "10 improvement points across a standalone abilities or breakout abilities; or 5 improvement points across keywords."

That to me implies you may add to a breakout from those 10 points, but that conflicts with the section 3.4 where it say you can not improve breakouts!

**Comment by AndreasDavour** [comment]
I realized this was kind of a duplicate, but please note my first point about section 2.1.1.1 though.

**Comment by iancooper** [comment]
Thanks for this.

**Comment by iancooper** [comment]
Fixed
