### ISSUE TITLE
What is an occupation and what is a distinguishing characteristic?

### ISSUE THREAD

**Issue by AndreasDavour** [ChaosiumInc/QuestWorlds#136]
In _3.1 As-You-Go Method_ you specify that the Concept is an Occupation and a Distinguishing Characteristic. Then there's a bullet point list of examples. Those examples are all an occupation, and a descriptive qualifier. It's very easy to think these are examples of Occupation _and_ Distinguishing Characteristic, but when you read further down that you get two abilities from your Concept you might get the idea that e.g. "haughty priestess" is an Distinguishing Characteristic, which begs the question of what's the Occupation, as clearly a priestess sounds like an occupation.

Maybe examples of Occupations as well if that's a separate thing, or more clearly show that "haughty" is one ability and "priestess" is another.

Capitalizations intentional on game terms.

**Comment by iancooper** [comment]
Thanks, I'll ponder

**Comment by AndreasDavour** [comment]
Sorry, but this has nothing to do with degrees!

**Comment by iancooper** [comment]
Those are examples of Occupation and Distinguishing Characteristic, though this was closed in error.

**Comment by iancooper** [comment]
@AndreasDavour Not sure why, but you seemed to relink the fewer degrees PR. I think it might have been GitHub being 'too smart' originally. I've unlinked again.

**Comment by AndreasDavour** [comment]
Weird. I did no linking intentionally at least. Could be it is trying to "user friendly" in some way then.

**Comment by iancooper** [comment]
Fixed
