### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by thibaultmeyer** [ChaosiumInc/QuestWorlds#139]
Hello,

I would like to initiate a repository to host the French translation of the QuestWorlds SRD. Do you think it is possible that it is hosted within the "ChaosiumInc" organization on GitHub?

Sincerely.

**Comment by iancooper** [comment]
Hello @thibaultmeyer. Do you want to mail me on ian@chaosium.com so that we can talk through translations, licensing etc. Then we can figure out where to host it. Here may well be the best place.
