### ISSUE TITLE
[Meta] Add issue category "Meta" (like this) for issues relating to repo itself.

### ISSUE THREAD

**Issue by jlaufersweiler** [ChaosiumInc/QuestWorlds#18]
I suggest a new category of issue subjects be added to the list in CONTRIBUTING.md and a corresponding Label be defined in the repo Issues section for matters not related to the content of the SRD as such, but rather to the repository itself, its organization, README.md, CONTRIBUTING.md, build scripts, etc.

This would allow housekeeping and tooling matters to be easily filtered or sorted apart from matters relating to the game itself.

One could imagine finer grained non-game-content categories, e.g. splitting build-script bug issues or community management off from general housekeeping, but that may be more trouble than it's worth at the project's current size. Any hotspots could always be split off should the need arise.

**Comment by jlaufersweiler** [comment]
By way of example, [I have an update to the README.md](https://github.com/ChaosiumInc/QuestWorlds/compare/master...jlaufersweiler:master) that introduces the project and publisher, and provides links to the legal info and contributing sections. I'd open an issue for that prior to submitting a PR, but the categories in CONTRIBUTING.md all specify issues relating to the rules text.

**Comment by iancooper** [comment]
Good suggestion, let me update for that change

**Comment by iancooper** [comment]
Fixed, thanks @jlaufersweiler
