### ISSUE TITLE
Section 3.2 Assigning Ability Ratings - Breakout Ratings?

### ISSUE THREAD

**Issue by dscarpenter** [ChaosiumInc/QuestWorlds#19]
Section 3.2, Assigning Ability Ratings, states: 

> Assign a starting rating of 17 to the ability you find most important or defining. Although most
> players consider it wisest to assign this rating to their occupational keyword, you don’t have to do
> this. Assign a rating of 17 to your distinguishing characteristic. In some cases, you may treat your
> distinguishing characteristic as a breakout ability from a keyword in this case, treat it as a +4.
> 
> All other abilities start at a rating of 13.

No mention is made in the section of the starting rating for **breakout abilities.**  

I believe "All other abilities start at a rating of 13" should be amended to read "All Abilities or Keywords start at a rating of 13 and all Breakout Abilities begin with a rating of +1."

Unless I'm missing something, which is quite possible. ;)

**Comment by iancooper** [comment]
Hmmm, let me check on that one. I suspect you are right, but suprised we don't have that anywhere

**Comment by dscarpenter** [comment]
If it is covered somewhere else, I think it probably bears repeating here.

**Comment by iancooper** [comment]
Added a PR #27 that discusses breakout starting abilities. It also moves the discussion of distinguishing characteristic as breakout to the same place

**Comment by iancooper** [comment]
Fixed by PR
