### ISSUE TITLE
PDF output messes up Section 1.3

### ISSUE THREAD

**Issue by mmarquee** [ChaosiumInc/QuestWorlds#20]
I guess that this means the section before it is messed up somehow

![image](https://user-images.githubusercontent.com/1595279/80722893-cd0da480-8af7-11ea-8107-b37c58d75af2.png)

**Comment by iancooper** [comment]
Thanks, this happens if we don't have whitespace at the end of the preceding file. We have fixed a lot of these, hopefully we will have them all soon

**Comment by iancooper** [comment]
PR #25 raised
