### ISSUE TITLE
Formatting of Sections 3.1 and 3.6 messes up. 

### ISSUE THREAD

**Issue by mmarquee** [ChaosiumInc/QuestWorlds#22]
The formatting of the stages of Section 3.1 get messed up. 

"1. Concept

The concept is a brief phrase, often just a couple of words that tells the GM and other players what you do and how you act. Start with a noun or phrase indicating your **occupation keyword** or area of expertise, and modify it with an adjective suggesting a **distinguishing characteristic**, a personality trait that defines you in broad strokes:"
"
should possibly be ...

"1.  Choose a **concept**. The concept is a brief phrase, often just a couple of words that tells the GM and other players what you do and how you act. Start with a noun or phrase indicating your **occupation keyword** or area of expertise, and modify it with an adjective suggesting a **distinguishing characteristic**, a personality trait that defines you in broad strokes:"

That way the sections will line up and the first section won't look oddly formatted.

**Comment by mmarquee** [comment]
![image](https://user-images.githubusercontent.com/1595279/80919665-20cff600-8d63-11ea-9494-b1b31b5bca2a.png)

**Comment by mmarquee** [comment]
Same is true in Section 3.6 as well.

**Comment by iancooper** [comment]
Thanks, I'll see what we can do

**Comment by iancooper** [comment]
Raised issue #26 using the suggested fix
