### ISSUE TITLE
Multi-way PvP contests

### ISSUE THREAD

**Issue by iancooper** [ChaosiumInc/QuestWorlds#23]
We don't have an explicit way to handle multi-way PvP contests.

As an example all the PCs are racing, and we want to determine who finishes first.

There is no easy way to do this, as most of the contest procedures are optimized for PCs acting alone or together against an opposition. This works fine because the opposition does not need individual roles. When Ben Hur takes part in the chariot race, most of the drivers are color to the actions of Messala and Ben Hur, who we focus the contest on. 

But if the chariot race was between many PCs it becomes hard to use the approach of contesting every PC against every other PC to determine who wins.

A better alternative is perhaps to rule that all PCs compete against the opposition of the race itself, but the one with the best result, and if tied better roll, wins out among the PCs. In an extended contest, this could be the most RP or AP.

Needs some thought, but this is a gap in some situations.

**Comment by sciencefish** [comment]
When competing in a race, the goal is to win usually by reaching the target first (5 laps, winning line, shortest time). Most races aren't combative - 100m, horse, car racing. So competing against the race is the best approach. In unusual cases like chariot, stock car, and pod racing it's combative. Is the advice to change the contest focus here, from the race to the other competitors?

**Comment by dscarpenter** [comment]
The goal is to win the race, and this works fine if you're just trying to determine if a single PC or a group of PCs win. If the intent is for several PCs to race against one another and you want to determine which of them actually won, it doesn't work as well. There is currently no mechanism to determine the winner if multiple PCs compete against each other in a PVP contest.

For our race contests in Valley of Plenty, I used the approach Ian describes: Everyone rolls against the race's resistance, and the best result wins. This worked well in our playtests, but that's an admittedly small sampling to base a decision on. 

I do think that situations like this will be common enough that they should be addressed with a specific, simple mechanism.

**Comment by iancooper** [comment]
@sciencefish this issue came up from what @dscarpenter was trying to do. I seem to recall it being an issue at times when I have played the game with these kind of contests.

I think the general case is multiple PCs enter a contest, only one can win. We want to avoid a combinatorial explosion of contests i.e. every PC against every other PC. As you say, the real opponent is the race. But who won?

The solution of using best result, with better roll on tied results seems elegant. Of course it only works for a simple contest. 

For long contests, some part of my brain thinks we could make highest RP or AP among the PCs work as a proxy. For chained contests, I assume that you 'damage' every losing PC each round.

**Comment by jlaufersweiler** [comment]
Chained contests seem like the way to go for zooming into a multi-stage race or the like. Leading at the end of one stage gets you an edge in the next, and coming from way behind is highly unlikely. 

That's if you favor credibility though. If you’re aiming for more drama-forward feel, a Scored Contest starts to look good. First to 5 wins, better rolls break ties, relative scores give spread.

**Comment by iancooper** [comment]
I guess it would be nice to figure out how to do it for all long contest types. I'd prefer the simple message to be - pick one long contest type.

First to five would work for scored contests, everyone rolls against the resistance.

But with chained contests, wouldn't penalties only accrue to the losers,. doesn't help with folks that keep beating the resistance. I guess you could go for everyone that fails drops out/falls behind, keep going until only one participant left. That feels more in keeping with the death spiral

**Comment by iancooper** [comment]
I'm thinking that for all of these the rule would be:

* Who had the better result?
* If one or more PCs are tied for the best result, who had the best 'margin'
* For a simple contest margin is diff between your roll and resistance; for long contests, highest RP, AP etc.
* if that is all the same, result is a tie

**Comment by jrutila** [comment]
Should it be mentioned that you have to win the contest, first? Or is it self-evident?
The result comparison, of course, takes care of that _if_ all the contestants have the same resistance target number. But do they always have that?
