### ISSUE TITLE
Resolving the missing formatting lines

### ISSUE THREAD

**Issue by sciencefish** [ChaosiumInc/QuestWorlds#24]
Can the linefeeds / spaces that make the PDF layout work be removed from the ends of individual markdown files and added in create_markdown.sh? eg [stackoverflow](https://stackoverflow.com/questions/8183191/concatenating-files-and-insert-new-line-in-between-files) ?

Being effectively invisible, It would stop them being left out or accidentally being edited in the section files.

**Comment by iancooper** [comment]
Possibly. We would have to then go through and remove all the surplus blank lines. So it might be worth considering, but let's maybe wait until it breaks again

**Comment by iancooper** [comment]
Closing this for now, let's re-open if this persists as an issue
