### ISSUE TITLE
[Housekeeping] Readme could be more informative.

### ISSUE THREAD

**Issue by jlaufersweiler** [ChaosiumInc/QuestWorlds#30]
The readme has a good primer on how Markdown is used in this project, but apart from the link to chaosium's site doesn't really tell much about the project. 

Ideally, it should provide a brief introduction to the project as well as direct readers to further information on the game, publisher, license, and how to contribute.

PR forthcoming.

**Comment by iancooper** [comment]
PR merged. Thanks @jlaufersweiler
