### ISSUE TITLE
Escalating contest mismatching options

### ISSUE THREAD

**Issue by jrutila** [ChaosiumInc/QuestWorlds#32]
2.6.2 - Escalating contest begins with:

If your GM chooses either the scored contests or chained contests form of long contest you can use an option called escalating contests.

And it ends to following sentence:

If you wish to use escalating contests, you need to choose scored contests as your long contest option.

The latter sentence is missing mention of the chained contest and it is also redundant.

**Comment by iancooper** [comment]
Thanks

**Comment by iancooper** [comment]
Fixed by #43
