### ISSUE TITLE
2.1.1 Ratings and Masteries

### ISSUE THREAD

**Issue by sciencefish** [ChaosiumInc/QuestWorlds#33]
From BRP, 9 hours ago, Martigan said:
1 : It is said in the SRD that  ''...the number in front of the M is now the target number you seek to roll or less to achieve a critical!. Where in HeroQuest 2nd we can see that ?
-----
2.1.1 Ratings and Masteries
[...]
The "M" after the rating signifies mastery. You have now reached a new order of excellence in that ability, such that your die rolls will almost always succeed. Unless opposed by similarly exalted resistance (see §2.3.5.2 for more details) the number in front of the M is now the target number you seek to roll or less to achieve a critical!

if you roll the number or less, you achieve a success, this is then always bumped by the mastery to a critical. 

Proposed change:

the number in front of the M is now the target number you seek to roll or less to achieve a **success. The mastery then bumps it to a critical!**

**Comment by dscarpenter** [comment]
I  have interpreted this to mean that if I have 10M, I now treat any roll of 10 or less as a critical, no bump required. All my rolls are successes (other than rolls of 20), and I can use Mastery to bump those to critical unless my Mastery is canceled by my opponent's. I may be reading the rule too literally, though.

**Comment by dscarpenter** [comment]
Looking at the SRD, I'm definitely wrong. **2.5.4** spells out the process.

I'd suggest revisiting the wording in 2.1.1 to clarify it. I'm probably not the only dense kid in the audience.

**Comment by iancooper** [comment]
Raised #44
