### ISSUE TITLE
[error] Typos 

### ISSUE THREAD

**Issue by Robin-Mitra** [ChaosiumInc/QuestWorlds#34]
This is my first issue on Github. Hope I am doing it right. I apologise if the phrases are not typos but deliberate. English isn’t my native tongue. 

2.1.3 "For a simple contest this can be often be" => "For a simple contest this can often be"

2.4 "If you GM accepts" => "If your GM accepts"

2.7 "with respect to in the previous" => "with respect to the previous"

2.9.1.5 "then you must succeed" => "you must succeed"

2.9.2 Clearly Inferior Opponents: "if the resistance you used in the contest" => "if the ability you used in the contest"

5.2.1 paragraph 6.i "A scored contest" => "A group scored contest"

6.5.2 "Metaphorical deaths from non-violent contests indicate a break you." => Never heard that expression. Maybe “a break with you”?

7.1.1 "Any time you one of your ratings" => "Any time one of your ratings"

7.1.1. "you may also improve up to three abilities or keywords of your choice increase by three points each" => "you may also improve up to three abilities or keywords of your choice by three points each"

8.2.3. "For a long contest, the penalty corresponds" => "For a group contest, the penalty corresponds"

9.1 "Assist In a scored contest, if you are unengaged you may use an assist to reduce the resource points" => "resolution points"

9.1 "Boost Spending points ahead of a group simple contest outcome" => “Boost Spending points after a group" Explanation: because in 4.5.3 it says "To overcome this flattening effect, if the outcome of a group simple contest is a tie or victory", also see Issue #11

9.1 "Contest … A contest may be simple (one roll) of extended (a series of rolls)" => "Contest … A contest may be simple (one roll) or long (a series of rolls).

9.1. "Degree of Victory or Defeat How well did you triumph, or how badly did you fail: Critical, Success, Failure, Fumble." => "Complete, Major, Minor, Marginal, or a Tie"

9.1 "Resistance The forces opposing the PC in a conflict, or concealing a secret that must be overcome by using an ability in a contest. One of: Nearly Impossible, Very High, High, Moderate, Low, Very Low." => "Extreme, Huge, Very High, High, Raised, Moderate, Low, Very Low, Tiny, Rock-bottom" (see 2.3.3.1)

**Comment by iancooper** [comment]
Thanks Robin, I'll work my way through them

**Comment by iancooper** [comment]
2.1.3 "For a simple contest this can be often be" => "For a simple contest this can often be"

I can't find this

**Comment by Robin-Mitra** [comment]
Hi Ian,

https://github.com/ChaosiumInc/QuestWorlds/blob/master/2.13_Ganging_Up.md
Line 1, sentence 2.

Robin

Am Sa., 13. Juni 2020 um 17:18 Uhr schrieb Ian Cooper <
notifications@github.com>:

**Comment by iancooper** [comment]
As 2.13 not 2.1.3 got it :-)

**Comment by iancooper** [comment]
Fixed as a batch on master

**Comment by Robin-Mitra** [comment]
Oops, sorry.
I also wanted to post some suggestions for changes tomorrow. I hope that is
alright.
