### ISSUE TITLE
[error] Mis-Numbered headers in 2.9

### ISSUE THREAD

**Issue by Robin-Mitra** [ChaosiumInc/QuestWorlds#35]
These numbers are mis-numbered: 
2.9.1.3 Pumped => 2.9.2.2
2.9.1.4 Invigorated => 2.9.2.3
2.9.1.5 Heroic => 2.9.2.4
2.9.1.6 BENEFITS OF VICTORY TABLE => 2.9.2.5
2.9.2 Clearly Inferior Opponents => 2.9.3

**Comment by iancooper** [comment]
Fixed, though 2.9.2 was made 2.9.2.6
