### ISSUE TITLE
[fix] The term “final action” has two different meanings

### ISSUE THREAD

**Issue by Robin-Mitra** [ChaosiumInc/QuestWorlds#38]
The term "final action" applies to both a single action after a contest (2.9.1.5) and to the attempt to re-enter an ongoing contest (5.3.5). To clarify this I suggest renaming the latter, as it is not really final if it succeeds (e.g. Retrieval/Re-Engaging Action).

**Comment by iancooper** [comment]
I used Second Chance

**Comment by Robin-Mitra** [comment]
I like that.
