### ISSUE TITLE
[fix] Healing difficulties correspond to the old resistances

### ISSUE THREAD

**Issue by Robin-Mitra** [ChaosiumInc/QuestWorlds#39]
2.9.3.3 Healing difficulties are low, moderate, high, very high. This corresponds to the old/HeroQuest resistances. However, with the new resistances introduced in 2.3.3.1. there is now “raised” between “moderate” and “high”. Leaving that out would create a non intuitive gap. I suggest changing it either to low, moderate, raised and high or to moderate, raised, high and very high.

**Comment by iancooper** [comment]
@Robin-Mitra Thanks, there may be a few of these kind of things that crept through, and it's great that you have found them
