### ISSUE TITLE
[fix] Plot edits need multiple players

### ISSUE THREAD

**Issue by Robin-Mitra** [ChaosiumInc/QuestWorlds#46]
7.2.1 Plot Edits: To spend 5 HP multiple players have to bundle their efforts, because players have only one or two HP available per session (7.1). It should be mentioned that this is possible.

**Comment by iancooper** [comment]
@Robin-Mitra I'm wondering with the lower number of hero points in QuestWorlds, if we should lower the cost of plot edits, as opposed to suggesting that this be combined spend.

BTW I am alright with allowing combined spend, but I wonder if we are not dealing with the actual issue

**Comment by Robin-Mitra** [comment]
1.	Yes, the cost of plot edits could be reduced, too (e.g. 0 to 3), as heropoints are more precious now. Nonetheless, if the whole group benefits from the edit I would not mind players combining their HP.

2.	Regarding Issue Simplification #54 I wonder if a rule set for plot edits is necessary at all. I require from my players to be creative anyway and to suggest editions to their character backgrounds, to NPC and to the world. If they are hesitant, I encourage them to do so. Naturally the GM has the final say in these matters. But if it is entertaining and does not screw up my plot, I allow it without the expenditure of heropoints. I think it is possible to keep the chapter Plot Edits (and the examples) but remove all rules regarding heropoints from it. Instead phrase it in a way to encourage using plot edits in consultation with the GM.

**Comment by iancooper** [comment]
@Robin-Mitra I am going to fix the magnitude of the cost in the main line, and once we have a simplified branch, and are reviewing this, we can look at the issue of whether this should cause hero points again.

**Comment by iancooper** [comment]
Raised #56
