### ISSUE TITLE
[fix] Augments with breakout abilities

### ISSUE THREAD

**Issue by Robin-Mitra** [ChaosiumInc/QuestWorlds#47]
2.4 "you may not use an ability to augment itself": Is it permitted to augment a breakout ability with another breakout ability of the same keyword? Whether or not it is allowed, should be mentioned here.

**Comment by jlaufersweiler** [comment]
Generally speaking, it is not permitted. This is one of the things that discourages players from just loading everything onto a single keyword.

I could see someone writing a game that uses package-style keywords allowing this, but that's not the assumption in the base rules.

**Comment by iancooper** [comment]
I would avoid it, not just for mechanical reasons, but generally because it would be uninteresting due to the fact that it would not tell us anything about your character.

I'll add a note.

**Comment by Robin-Mitra** [comment]
Agreed. 
The note will be helpful.

**Comment by iancooper** [comment]
Raised #57
