### ISSUE TITLE
[fix] Spending heropoints on Boosts

### ISSUE THREAD

**Issue by Robin-Mitra** [ChaosiumInc/QuestWorlds#48]
4.5.3. Does that mean players can spend heropoints twice, i.e. both during the contest to bump their individual outcomes and after the contest to bump the overall outcome?

**Comment by iancooper** [comment]
Yes, in theory there is nothing to stop individuals impacting their outcome and then changing the overall outcome. 

Do you feel this needs calling out?

**Comment by Robin-Mitra** [comment]
Yes, I think a short sentence could be added to clearify this, only to prevent questions.

**Comment by iancooper** [comment]
Raised #58
