### ISSUE TITLE
[enhancement] The term Extended Contests makes QW incompatible with HQ 

### ISSUE THREAD

**Issue by Robin-Mitra** [ChaosiumInc/QuestWorlds#49]
5.3. "Extended Contest" this term makes QW incompatible with HQ.

Explanation: Questworlds changes the HeroQuest term of Extended Contests to Scored Contests and introduces a new kind of Contest now called Extended Contests. Players who read HeroQuest supplements and the Questworlds rules will thereby be confused. 

Recommendation: I recommend finding a new term for Extended Contest (QW), for example Bidding Contest or Wager Contest.

**Comment by iancooper** [comment]
This is historical. Extended Contests was the name give to a long contest using APs based mechanic in HW and HQ 1.0. The first draft of HQ 2 created long contests, which included the original extended contest and added scored contests. It was decided in HQ2 to drop extended contests and just go with scored contests. it was then decided to rename those to extended contests.

This was an aggressive choice to signal the end of extended contests.

With the SRD we wanted to include the model that HW and HQ 1 used, partially for completeness, but also as some prefer them still.

I think they work better for some types of game, particularly supers.

Changing them away from Extended contests to reintroduce them creates just as much confusion, so I opted to revert to the original naming

Remember that the SRD is a complete document. A game like HQG ought to really pick one, scored contests in that example, and stick with it, so the confusion is low in practice.

**Comment by Robin-Mitra** [comment]
Understood.
