### ISSUE TITLE
[enhancement] The terms Minor and Complete are misleading for new players

### ISSUE THREAD

**Issue by Robin-Mitra** [ChaosiumInc/QuestWorlds#50]
Explanation 1: In my experience newbie players understand the term Minor Success (2.8) as something less than full. If they hear only the word they expect to get less than 100% of the prize, although that is exactly what they get. 
Recommendation: Change Minor Success/Defeat to Normal/Regular or something similar

Explanation 2: Players tend to understand Complete Success (2.8) as being all there is to get. If they hear only the word they expect to get 100% of the prize, although they will get far more than that. 
Recommendation: Change Complete Success/Defeat to Great/Extreme or something similar.

**Comment by jlaufersweiler** [comment]
Quick note: these are Victory contest outcomes, not Success roll results.

**Comment by Robin-Mitra** [comment]
Yes, my bad. I meant victories not successes. The point about "minor" and "complete" remains, though.

**Comment by iancooper** [comment]
I don't really want to change this. I understand your point, but narrating outcomes falls on the GM not the PC, explicitly. And whilst a GM may invite suggestions it's an important part of how the game works to give the GM narrative control. So the term is really for the GM.

As we will spend some time in the GM's book discussing these outcomes, I don't think a name change is going to make enough difference that we want to throw people with new names here.

**Comment by iancooper** [comment]
@Robin-Mitra See the discussion on simplification instead

**Comment by Robin-Mitra** [comment]
ok
