### ISSUE TITLE
[Fix] Should it be an auto-victory not an auto-success

### ISSUE THREAD

**Issue by iancooper** [ChaosiumInc/QuestWorlds#52]
Whilst it is a term that everyone has internalized, and thus we need to think twice about changing it, automatic success suffers from the problem that success/failure relates to your roll, not the outcome, which is victory/defeat. To be correct, if you automatically achieve your goal, that would be an _automatic victory_ and not an automatic success.

We would also need to align with Arduous Auto-Success as _Arduous Auto-Victory_ and a Costly Success as a _Costly Victory_.

**Comment by jlaufersweiler** [comment]
Agreed. It would harmonize with Phyrric Victory as well.

**Comment by Robin-Mitra** [comment]
Agreed.

**Comment by iancooper** [comment]
Already fixed, nothing to do here
