### ISSUE TITLE
Version number not fully updated - 0.11 to 0.12

### ISSUE THREAD

**Issue by SteveHammatt** [ChaosiumInc/QuestWorlds#65]
In section 0.1, the version number hasn't been updated from 0.11 to 0.12 for all occurrences.

The first paragraph of section 0.1 has two occurrences of "QWSRD0.11" which should be "QWSRD0.12" to reflect the current version.

**Comment by iancooper** [comment]
Fixed on the current branch - will be fixed if we roll that into the main line
