### ISSUE TITLE
typo in 2.7.2 Benefits

### ISSUE THREAD

**Issue by scottalthoff** [ChaosiumInc/QuestWorlds#70]
Your GM may assign a penalty to reflect this benefit.
should be:
Your GM may assign a bonus to reflect this benefit.

**Comment by scottalthoff** [comment]
The next line appears to be superfluous: "Your GM will assign a penalty depending on how good they feel the benefits are. Your GM should assign a bonus that corresponds to a rank: +3, +6, +9, +M, or +M2."

**Comment by iancooper** [comment]
@scottalthoff Fixed directly in master. Thanks for spotting this one
