### ISSUE TITLE
[Error] A few typos in chapter 2

### ISSUE THREAD

**Issue by eiderweb** [ChaosiumInc/QuestWorlds#77]
2.1.2
* The final sentence in the third paragraph should read "When both you and the resistance have masteries the**y** cancel out." (missing **y** highlighted in bold)

2.3.1.1
* The last sentence in the 6th paragraph should read: "It will probably be **a** penalty involving..." (missing word highlighted in bold)
* The sentence before the final list should read "At i**t**s most basic, a**n** assured contest can be summarized as follows:" (missing letters highlighted in bold)

2.3.1.2
* The first sentence should begin: "The simple contest **is** QuestWorlds' primary resolution mechanic..." (missing word highlighted in bold)

2.3.7
* The penultimate sentence of the first para should begin: "A bump down reduces **the** result by one step..." (missing word highlighted in bold)
* The last sentence should read: "Bumps always affect results not outcomes, although the outcome could change as a**n** effect of gaining a different result." (missing letter highlighted in bold)

2.3.7.1
* The last sentence should read: "If the resistance **is** one or more levels of mastery greater than you, your GM can bump **up** their roll."  (missing words highlighted in bold)

**Comment by iancooper** [comment]
Thanks
