### ISSUE TITLE
Typos in §0.1, §2.3.1.1, and §2.3.1.2

### ISSUE THREAD

**Issue by eggdropsoap** [ChaosiumInc/QuestWorlds#83]
### §01

In the first sentence, the SRD version number 0.41 isn't consistently updated. The second use still says 0.4:

> The QuestWorlds System Reference Document 0.41 (“QWSRD0.41”) describes the rules of QuestWorlds. You may incorporate the rules as they appear in **QWSRD0.4**, wholly or in part[…]

### §2.3.1.1 and §2.3.1.2

The sentences right before the sections' respective numbered lists say "At is most basic" but should say "At its most basic".

**Comment by iancooper** [comment]
Thanks
