### ISSUE TITLE
Glossaries could take advantage of definition-list Markdown

### ISSUE THREAD

**Issue by eggdropsoap** [ChaosiumInc/QuestWorlds#84]
For improved semantics and better output formatting even with default settings, the glossaries in §10.1 and §10.7 could use the pandoc-supported [definitions-lists markdown](https://pandoc.org/MANUAL.html#definition-lists). This produces nicely-formatted lists of terms with hanging heads, as common in RPG glossaries.

Definition-lists also produce semantic markup in the output formats, making the glossaries potentially behave better in HTML screen-readers, and making them easier to style in CSS and in TeX templates.

That is, instead of writing:

    **Ally** A **supporting character** of roughly equal ability to your own.

    **AP** Abbreviation for Advantage Point.

one can write:

    **Ally**
    : A **supporting character** of roughly equal ability to your own.

    **AP**
    : Abbreviation for Advantage Point.

… and have HTML, RTF, and LaTeX all format that correctly "for free" with the existing pandoc commands in `create_formats.sh`.

For a full diff demonstrating both markdown files with this change applied, see https://github.com/eggdropsoap/QuestWorlds/commit/c9e2a75765d5b6e2e90eccadfb22ab8996127995.

**Comment by iancooper** [comment]
Wow this is really useful. Thanks

**Comment by iancooper** [comment]
@eggdropsoap Did you want to submit a PR with this change?

**Comment by eggdropsoap** [comment]
I can do that!
