### ISSUE TITLE
[Typos] various

### ISSUE THREAD

**Issue by Robin-Mitra** [ChaosiumInc/QuestWorlds#96]
After some months of absence I read the complete text again and found some typos. 

  |  
-- | --
2.1.2 Scores, Ratings and   Masteries | Second paragraph: “we use of   tiers of” change to “we use tiers of”
2.1.2 Scores, Ratings and Masteries | Fourth paragraph: “… and have a   higher chance of a critical   from rolling under the TN.” Is   that part of the sentence not redundant with the first part?
2.1.2 Scores, Ratings and Masteries | Seventh paragraph: “Multiple masteries result in multiple bumps up, so with two masteries a critical bumps to a success.” Shouldn’t   that be a fumble instead of a critical?
2.3.1.1 Assured Contest | First Paragraph: “We call these   kinds or contests” change to “We call these kinds of contests”
2.3.6.1 Narrating Outcomes | “You GM” change to “Your GM”
2.3.6.1 Narrating Outcomes | “But the GM is the final arbiter   of the how the story progresses” delete “the”
2.3.7.3 Bump Down with Mastery | Fourth sentence: „If you critical“. Change to “if you have a critical”
2.6 Flaws | Last sentence: “that means one of your flaw means would“ change to “that means one of your flaws would”
2.6.2 Act according to your flaw | First paragraph: “may prevent your” change to “may   prevent you”
2.7.1.2 Ending a PC's story | Last paragraph: “that the group is   telling, In this case” replace comma with full stop
3.0 Character Creation | First sentence: “that fits in with   the genre of game” add: “the” before game
4.1 Simple Contest | “Roll a D20 to determine your success or failure, then   apply any bumps. Your GM does the same   for the resistance. Compare your   rolled number with your TN to see   how well you succeeded or failed with your ability.   Remember to apply any bumps from masteries or story points.” Sentences 3   and 4 seem to be redundant with sentence 1, or am I missing something? I know   that repetition can clarify things but here it makes it rather cumbersome to   read.
4.2.1 Procedure | Last paragraph, second sentence: “It is possible that, as a   result, that your GM will suffer” delete “that” and change “GM” to “PC”
5.1.2 Resolution Points | The first dash uses a reversed   syntax compared to the following sentences. I recommend turning it around, i.e.   “You score one resolution point if you have a better roll on the same result.”
5.1.4 Parting Shot | First sentence: “you may attempt   to gain another prize from   your opponent suffers” delete “suffers”
5.2.1 Procedure | “4. The PCs to choose their   opponents” delete “to”
5.2.4 Assists | Fifth Paragraph: “you reduce then   resolution points by 2” change   “then” to “the”
5.2.4 Followers | This should be 5.2.5, the   following titles should be changed accordingly.
5.3.1 Procedure | 4.c. and 4.g.: “Compare the   results of the two results“ change to „Compare   the two results“
5.4.1 Procedure | 6.c.: “Compare the results of the   two results“ change to „Compare the two results“
5.3.6 Disengaging | Change plusminus to §
5.3.12 AP Gifting | Change plusminus to §
5.3.6 Disengaging | Change number to 5.3.8, and the   following titles accordingly
5.3.12 AP Gifting | Last sentence: “On a victory you transfer that   number of the participant” change to “On a victory   you transfer that number to the participant”
5.4.2 Group Extended   Contest Outcomes | “If you lost, your benefit” change to “If your team lost, your benefit”
5.4.2 Group Extended   Contest Outcomes | “your consequence should not limit   the prize which your team one“   change “one” to “won”
5.4.3 Second Chance | “Even if you succeed, a consequences applies”   change “consequences” to „ consequence”
6.4 Contacts | „Contacts provide your information“   change “your” to “you”
7.0 Story Points | Change QuestWorlds to QuestWorlds‘
7.1 Story Point Pool | Change „You do not agreement“ to “You   do not need agreement”
8.1 Earning Experience   Points | “You do not gain experience points if any of   the following apply:” This is redundant with the following dashes. I   recommend changing it to “Remember:” or “Note:”
9.1.1 Defining Resources | “Diplomacy — the relationships   with other groups though” change “though” to “through”
10.1 Glossary of Terms | “resistance class” (multiple occurrences)   I think this has been replaced by rank
10.1 Glossary of Terms | “Defensive Response : (…) which reduces the resource points” change “resource” to “resolution”
10.1 Glossary of Terms | „state of adversity“ I think this has been replaced by   rank
10.1 Glossary of Terms | “hurt“ I think this has been replaced by   rank
10.1 Glossary of Terms | “Extreme, Huge,   Very High, High, Raised, Moderate, Low, Very Low, Tiny, Rock-bottom.” I think this   has been replaced by rank
10.1 Glossary of Terms | “Stretch : A penalty applied to an ability because it is   stretches” delete „is“

**Comment by davecake** [comment]
Came here to note the same issue with 4.2.1

**Comment by iancooper** [comment]
Thanks for thi @Robin-Mitra. Only didn't apply 2.373
