### ISSUE TITLE
[Error] 4 or 5 resolution points on crit vs fumble?

### ISSUE THREAD

**Issue by Robin-Mitra** [ChaosiumInc/QuestWorlds#97]
5.1.1 Procedure   And   5.2.1 Procedure | i. “the winner scores a number of resolution points (RPs) to   their tally, which varies between 1 and 5“       However, 5.1.2 Resolution point   says: “You score four resolution points   for three levels of difference, which is a critical   vs. fumble.” This corresponds   with 5.2.4 Assists.
-- | --

**Comment by iancooper** [comment]
Thanks
