### ISSUE TITLE
[Enhancement] Resistance modifiers explained without base resistance

### ISSUE THREAD

**Issue by Robin-Mitra** [ChaosiumInc/QuestWorlds#98]
2.3.3. explains Rank and 2.3.3.1. shows the Ranks table. However, these are only modifiers, and up to that point it is unclear what number they are modifying. 
Only 456 words later, at the end of chapter "2.3.4 Resistance" we learn that the base resistance is 14 and all modifiers previously mentioned apply to that number. I recommend switching the chapters 2.3.3. and 2.3.4

**Comment by iancooper** [comment]
Moved the positioning of text declaring default resistance
