### ISSUE TITLE
[Fix] Consequences and benefits, how can +M2 be applied?

### ISSUE THREAD

**Issue by Robin-Mitra** [ChaosiumInc/QuestWorlds#99]
2.7.1 Consequences: “Your GM should assign a penalty that corresponds to a rank: +3, +6, +9, +M, or +M2.” and
2.7.2 Benefits: “Your GM should assign a bonus that corresponds to a rank: +3, +6, +9, +M, or +M2.” 

As explained a few sentences later Critical vs. Fumble is +M. So how can a +M2 ever be applied?

**Comment by iancooper** [comment]
Thanks
